//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrimerPruebaDeLibreria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Libros
    {
        public int Id { get; set; }
        public string ISBN { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        public string Autor { get; set; }
        public string Autor2 { get; set; }
        public string Autor3 { get; set; }
        public int IdAutor { get; set; }
        public Nullable<int> IdAutor2 { get; set; }
        public Nullable<int> IdAutor3 { get; set; }
        public string Editorial { get; set; }
        public Nullable<int> IdEditorial { get; set; }
        public string Genero { get; set; }
        public string SubGenero { get; set; }
        public string SubGenero2 { get; set; }
        public int IdGenero { get; set; }
        public Nullable<int> IdSubGenero { get; set; }
        public Nullable<int> IdSubGenero2 { get; set; }
        public System.DateTime FechaPublicacion { get; set; }
        public int Stock { get; set; }
        public decimal Precio { get; set; }
    
        public virtual Autores Autores { get; set; }
        public virtual Autores Autores1 { get; set; }
        public virtual Autores Autores2 { get; set; }
        public virtual Editoriales Editoriales { get; set; }
        public virtual Generos Generos { get; set; }
        public virtual Generos Generos1 { get; set; }
        public virtual Generos Generos2 { get; set; }
    }
}
